---
title: "data science ii final project"
author: "Yiying Chen yc4776"
date: "2026-05-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, warning=FALSE, message=FALSE}
library(tidymodels)
library(dplyr)
library(tidyr)
library(ggplot2)
library(caret)
library(pROC)
library(e1071)
library(patchwork)
library(gridExtra)
library(knitr)
```

# Data cleansing and NA value check
```{r data_cleaning}
# Load the full dataset (loads object `dat` into your environment)
load("severity.RData")

# Make sure there is no na value in original dataset
sum(is.na(dat))

# Set the random seed to the last 4 digits of YOUR UNI
set.seed(4776)

# Randomly sample 1,000 participants for your analysis
severity <- dat[sample(nrow(dat), 1000), ]

# convert categorical variables into factors
# avoid leaving blanks in the label
severity <- severity |>
  select(-id) |>
  mutate(
    gender = factor(gender, levels = c(0, 1), labels = c("Female", "Male")),
    race = factor(race, levels = c(1, 2, 3, 4), labels = c("White", "Asian", "Black", "Hispanic")),
    smoking = factor(smoking, levels = c(0, 1, 2), labels = c("Never_smoked", "Former_smoker", "Current_smoker")),
    diabetes = factor(diabetes, levels = c(0, 1), labels = c("No", "Yes")),
    hypertension = factor(hypertension, levels = c(0, 1), labels = c("No", "Yes")),
    vaccine = factor(vaccine, levels = c(0, 1), labels = c("Not_vaccinated", "Vaccinated")),
    severity = factor(severity, levels = c(0, 1), labels = c("Not_severe", "Severe"))
  )

```

# Statistical summary
```{r summary_statistics}
# size of original dataset
dim(dat)

# summary of 1000 random samples
summary(severity)

# obtain the mean value of continuous variable by severity
mean_continuous =
  severity |>
  group_by(severity) |>
  summarise(
    n = n(),
    age_mean = round(mean(age), 1),
    height_mean = round(mean(height), 1),
    weight_mean = round(mean(weight), 1),
    bmi_mean = round(mean(bmi), 1),
    SBP_mean = round(mean(SBP), 1),
    LDL_mean = round(mean(LDL), 1),
    depression_mean = round(mean(depression), 1)
  )

kable(mean_continuous)

# obtain the proportion of continuous variable by severity
prop_categorical =
  severity |>
  select(severity, gender, race, smoking, diabetes, hypertension, vaccine) |>
  pivot_longer(
    cols = -severity,
    names_to = "variable",
    values_to = "category"
  ) |>
  count(severity, variable, category) |>
  group_by(severity, variable) |>
  mutate(percent = round(n / sum(n) * 100, 1))

kable(prop_categorical)
```
# EDA
```{r data_visualization}
# histogram plots for continuous variables distribution
severity |>
  select(age, height, weight, bmi, SBP, LDL, depression) |>
  pivot_longer(cols = everything(),
               names_to = "variable",
               values_to = "value") |>
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30, fill = "skyblue", color = "black") +
  facet_wrap(~ variable, scales = "free", ncol = 3) +
  theme_minimal() +
  labs(
    title = "Distribution of Continuous Variables",
    x = "Value",
    y = "Count"
  )

# box plots to observe the relationship between each continuous variable with response variable severity
severity |>
  select(severity, age, height, weight, bmi, SBP, LDL, depression) |>
  pivot_longer(
    cols = -severity,
    names_to = "variable",
    values_to = "value"
  ) |>
  ggplot(aes(x = severity, y = value)) +
  geom_boxplot(fill = "skyblue", color = "black") +
  facet_wrap(~ variable, scales = "free_y", ncol = 3) +
  theme_minimal() +
  labs(
    title = "Continuous Variables by COVID-19 Severity",
    x = "COVID-19 Severity",
    y = "Value"
  )

# proportion bar plots to observe the relationship between each categorical variable with response variable severity
severity |>
  select(severity, gender, race, smoking, diabetes, hypertension, vaccine) |>
  pivot_longer(
    cols = -severity,
    names_to = "variable",
    values_to = "category"
  ) |>
  ggplot(aes(x = category, fill = severity)) +
  geom_bar(position = "fill", color = "black") +
  facet_wrap(~ variable, scales = "free_x", ncol = 3) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  labs(
    title = "Proportion of Categorical Variables by severity group",
    x = "Category",
    y = "Proportion",
    fill = "Severity"
  )
```

```{r model_prep}
# Randomly split the data into 80:20
set.seed(4776)
data_split <- initial_split(severity, prop = 0.8)
training_data <- training(data_split)
testing_data <- testing(data_split)

# set up cross validation control
ctrl <- trainControl(method = "cv", number = 10, 
                     summaryFunction = twoClassSummary, 
                     classProbs = TRUE, savePredictions = "final")
```

# Logistic regression
```{r logistic_regression}
set.seed(4776)

# train logistic regression model with CV
model.glm <- train(severity ~ ., data = training_data,
                   method = "glm",
                   metric = "ROC",
                   trControl = ctrl)

# predictions on test data
glm.pred.class <- predict(model.glm, newdata = testing_data)
glm.pred <- predict(model.glm, newdata = testing_data, type = "prob")[,"Severe"]
```

# Penalized logistic regression
```{r penalized_logistic_regression}
# define tuning grid for penalized logistic regression
glmnGrid <- expand.grid(.alpha = seq(0, 1, length = 21),
                        .lambda = exp(seq(-8, -1, length = 50)))

# train penalized logistic regression model with CV
set.seed(4776)
model.glmn <- train(severity ~ ., data = training_data,
                    method = "glmnet",
                    tuneGrid = glmnGrid,
                    metric = "ROC",
                    trControl = ctrl)

# display best tuning parameters
model.glmn$bestTune

# predictions on test data 
glmn.pred.class <- predict(model.glmn, newdata = testing_data)
glmn.pred <- predict(model.glmn, newdata = testing_data, type = "prob")[,"Severe"]
```

# Boosting
```{r boosting}
# set up the grid for boosting model
gbmA.grid <- expand.grid(n.trees = c(500, 1000, 2000, 3000, 5000),
                         interaction.depth = 1:4,
                         shrinkage = c(0.001, 0.005, 0.01),
                         n.minobsinnode = 10)

set.seed(4776)

# train boosting model with CV
model.gbm <- train(severity ~ . ,
                  training_data,
                  tuneGrid = gbmA.grid,
                  trControl = ctrl,
                  method = "gbm",
                  distribution = "adaboost",
                  metric = "ROC",
                  verbose = FALSE)

# predictions on test data 
gbm.pred.class <- predict(model.gbm, newdata = testing_data)
gbmA.pred <- predict(model.gbm, newdata = testing_data, type = "prob")[,"Severe"]
```

# SVM
```{r SVM}
# set up the grid for SVM model
svm_grid <- expand.grid(sigma = c(0.001, 0.005, 0.01, 0.05),
                        C = c(0.25, 0.5, 1, 2, 4))

set.seed(4776)

# train SVM model with CV
model.svm <- train(severity ~ .,
                   data = training_data,
                   method = "svmRadial",
                   trControl = ctrl,
                   preProcess = c("center", "scale"),
                   tuneGrid = svm_grid,
                   metric = "ROC")

# predictions on test data
svm.pred.class <- predict(model.svm, newdata = testing_data)
svm.pred <- predict(model.svm, newdata = testing_data, type = "prob")[,"Severe"]
```

# cross validation
```{r CV_plots, warning=FALSE, message=FALSE}
# CV plots for penalized logistic regression
p_glmn <- ggplot(model.glmn, highlight = TRUE) +
  labs(title = "Penalized Logistic Regression Cross Validation Plot") +
  theme(plot.title = element_text(hjust = 0.5))

# CV plots for boosting
p_gbm <- ggplot(model.gbm, highlight = TRUE) +
  labs(title = "Boosting Cross Validation Plot") +
  theme(plot.title = element_text(hjust = 0.5))

# CV plots for SVM
p_svm <- ggplot(model.svm, highlight = TRUE) +
  labs(title = "SVM Cross Validation Plot") +
  theme(plot.title = element_text(hjust = 0.5))

# combine the plots into one panel
(p_gbm + p_svm) / p_glmn +
  plot_layout(heights = c(1, 1.2))
```

```{r model_training_validation}
# compare models using resampling
res <- resamples(list(GLM = model.glm,
                      GLMN = model.glmn,
                      Boosting = model.gbm,
                      SVM = model.svm))
summary(res)

# boxplot of ROC performance for all models
p_bw <- bwplot(res, metric = "ROC")

# dotplot of ROC performance for all models
p_dot <- dotplot(res, metric = "ROC")

# combine the plots into one panel
grid.arrange(p_bw, p_dot, ncol = 2)
```

# model selection
```{r model_selection, warning=FALSE, message=FALSE}
# compute ROC for each model
roc.glm <- roc(testing_data$severity, glm.pred)
roc.glmn <- roc(testing_data$severity, glmn.pred)
roc.gbmA <- roc(testing_data$severity, gbmA.pred)
roc.svm <- roc(testing_data$severity, svm.pred)

# plot the roc curve
plot(roc.glm, legacy.axes = TRUE, main = "ROC Curves")
plot(roc.gbmA, add = TRUE, col = 2)
plot(roc.svm, add = TRUE, col = 3)
plot(roc.glmn, add = TRUE, col = 4)
legend("bottomright", 
       legend = c(paste0("GLM (AUC=", round(roc.glm$auc, 3), ")"),
                  paste0("GLMN (AUC=", round(roc.glmn$auc, 3), ")"),
                  paste0("GBM (AUC=", round(roc.gbmA$auc, 3), ")"),
                  paste0("SVM (AUC=", round(roc.svm$auc, 3), ")")),
       col = 1:4, lwd = 2)

# calculate AUC values for each model
auc <- c(roc.glm$auc[1], roc.glmn$auc[1], roc.gbmA$auc[1], roc.svm$auc[1])
auc

# Accuracy table for four models
conf_matrix_glm <- confusionMatrix(glm.pred.class, testing_data$severity)
conf_matrix_glmn <- confusionMatrix(glmn.pred.class, testing_data$severity)
conf_matrix_gbm <- confusionMatrix(gbm.pred.class, testing_data$severity)
conf_matrix_svm <- confusionMatrix(svm.pred.class, testing_data$severity)

conf_matrix_glm$overall["Accuracy"]
conf_matrix_glmn$overall["Accuracy"]
conf_matrix_gbm$overall["Accuracy"]
conf_matrix_svm$overall["Accuracy"]
```

# variable importance
```{r variable_importance}
# variable importance of penalized logistic regression model (best model)
glmn_imp <- varImp(model.glmn)
plot(glmn_imp, main = "Variable Importance from Penalized Logistic Regression")

# Check coefficients to observe the direction of impact
coef(model.glmn$finalModel, s = model.glmn$bestTune$lambda) 
```

# Risk score
```{r risk_score}
# predict probability from penalized logistical regression (best model)
glmn.pred

# visulized distribution of the probability
risk_df <- data.frame(risk_score = glmn.pred,
                      severity = testing_data$severity)

ggplot(risk_df, aes(x = risk_score, fill = severity)) +
  geom_histogram(bins = 30, alpha = 0.6, position = "identity", color = "black") +
  scale_fill_manual(values = c("Not_severe" = "blue", "Severe" = "red")) +
  labs(
    title = "Distribution of Predicted Risk Scores",
    x = "Predicted Probability of Severe Infection",
    y = "Count",
    fill = "True Severity"
  ) +
  theme_minimal()
```
